application: kreved-gold
version: 1-10
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 (.*/junk)|
 (.*\.bak)|
 (makeup)
 )$
 