package com.appspot.milkydb.client;

import com.google.gwt.core.client.EntryPoint;
import com.google.gwt.user.client.ui.Label;
import com.google.gwt.user.client.ui.MultiWordSuggestOracle;
import com.google.gwt.user.client.ui.RootPanel;
import com.google.gwt.user.client.ui.SuggestBox;
import com.google.gwt.user.client.ui.VerticalPanel;

public class MilkyClient implements EntryPoint {

	private final SuggestBox suggestBox = new SuggestBox(
			new MultiWordSuggestOracle() {
				{
					add("Россия");
					add("Румыния");
					add("Украина");
					add("Англия");
					add("Америка");
					add("Ватикан");
					add("Венгрия");
					add("Великобритания");
					add("Afghanistan");
					add("Albania");
					add("Algeria");
					add("American Samoa");
					add("Andorra");
					add("Angola");
					add("Anguilla");
					add("Antarctica");
					add("Antigua And Barbuda");
					add("Argentina");
					add("Armenia");
					add("Aruba");
					add("Australia");
					add("Austria");
					add("Azerbaijan");
					add("Bahamas");
					add("Bahrain");
					add("Bangladesh");
					add("Barbados");
					add("Belarus");
					add("Belgium");
					add("Belize");
					add("Benin");
					add("Bermuda");
					add("Bhutan");
					add("Bolivia");
					add("Bosnia And Herzegovina");
					add("Botswana");
					add("Bouvet Island");
					add("Brazil");
					add("British Indian Ocean Territory");
					add("Brunei Darussalam");
					add("Bulgaria");
					add("Burkina Faso");
					add("Burundi");
					add("Cambodia");
					add("Cameroon");
					add("Canada");
					add("Cape Verde");
					add("Cayman Islands");
					add("Central African Republic");
					add("Chad");
					add("Chile");
					add("China");
					add("Christmas Island");
					add("Cocos (Keeling) Islands");
					add("Colombia");
					add("Comoros");
					add("Congo, The Democratic Republic Of The");
					add("Congo");
					add("Cook Islands");
					add("Costa Rica");
					add("Cote D''ivoire");
					add("Croatia");
					add("Cuba");
					add("Cyprus");
					add("Czech Republic");
					add("Denmark");
					add("Djibouti");
					add("Dominica");
					add("Dominican Republic");
					add("East Timor");
					add("Ecuador");
					add("Egypt");
					add("El Salvador");
					add("Equatorial Guinea");
					add("Eritrea");
					add("Estonia");
					add("Ethiopia");
					add("Falkland Islands (Malvinas)");
					add("Faroe Islands");
					add("Fiji");
					add("Finland");
					add("France");
					add("French Guiana");
					add("French Polynesia");
					add("French Southern Territories");
					add("Gabon");
					add("Gambia");
					add("Georgia");
					add("Germany");
					add("Ghana");
					add("Gibraltar");
					add("Greece");
					add("Greenland");
					add("Grenada");
					add("Guadeloupe");
					add("Guam");
					add("Guatemala");
					add("Guinea-Bissau");
					add("Guinea");
					add("Guyana");
					add("Haiti");
					add("Heard Island And Mcdonald Islands");
					add("Holy See (Vatican City State)");
					add("Honduras");
					add("Hong Kong");
					add("Hungary");
					add("Iceland");
					add("India");
					add("Indonesia");
					add("Iran, Islamic Republic Of");
					add("Iraq");
					add("Ireland");
					add("Israel");
					add("Italy");
					add("Jamaica");
					add("Japan");
					add("Jordan");
					add("Kazakstan");
					add("Kenya");
					add("Kiribati");
					add("Korea, Democratic People''s Republic Of");
					add("Korea, Republic Of");
					add("Kuwait");
					add("Kyrgyzstan");
					add("Lao People''s Democratic Republic");
					add("Latvia");
					add("Lebanon");
					add("Lesotho");
					add("Liberia");
					add("Libyan Arab Jamahiriya");
					add("Liechtenstein");
					add("Lithuania");
					add("Luxembourg");
					add("Macau");
					add("Macedonia, The Former Yugoslav Republic Of");
					add("Madagascar");
					add("Malawi");

					add("Malaysia");
					add("Maldives");
					add("Mali");
					add("Malta");
					add("Marshall Islands");
					add("Martinique");
					add("Mauritania");
					add("Mauritius");
					add("Mayotte");
					add("Mexico");
					add("Micronesia, Federated States Of");
					add("Moldova, Republic Of");
					add("Monaco");
					add("Mongolia");
					add("Montserrat");
					add("Morocco");
					add("Mozambique");
					add("Myanmar");
					add("Namibia");
					add("Nauru");
					add("Nepal");
					add("Netherlands Antilles");
					add("Netherlands");
					add("New Caledonia");
					add("New Zealand");
					add("Nicaragua");
					add("Niger");
					add("Nigeria");
					add("Niue");
					add("Norfolk Island");
					add("Northern Mariana Islands");
					add("Norway");
					add("Oman");
					add("Pakistan");
					add("Palau");
					add("Palestinian Territory, Occupied");
					add("Panama");
					add("Papua New Guinea");
					add("Paraguay");
					add("Peru");
					add("Philippines");
					add("Pitcairn");
					add("Poland");
					add("Portugal");
					add("Puerto Rico");
					add("Qatar");
					add("Reunion");
					add("Romania");
					add("Russian Federation");
					add("Rwanda");
					add("Saint Helena");
					add("Saint Kitts And Nevis");
					add("Saint Lucia");
					add("Saint Pierre And Miquelon");
					add("Saint Vincent And The Grenadines");
					add("Samoa");
					add("San Marino");
					add("Sao Tome And Principe");
					add("Saudi Arabia");
					add("Senegal");
					add("Seychelles");
					add("Sierra Leone");
					add("Singapore");
					add("Slovakia");
					add("Slovenia");
					add("Solomon Islands");
					add("Somalia");
					add("South Africa");
					add("South Georgia And The South Sandwich Islands");
					add("Spain");
					add("Sri Lanka");
					add("Sudan");
					add("Suriname");
					add("Svalbard And Jan Mayen");
					add("Swaziland");
					add("Sweden");
					add("Switzerland");
					add("Syrian Arab Republic");
					add("Taiwan, Province Of China");
					add("Tajikistan");
					add("Tanzania, United Republic Of");
					add("Thailand");
					add("Togo");
					add("Tokelau");
					add("Tonga");
					add("Trinidad And Tobago");
					add("Tunisia");
					add("Turkey");
					add("Turkmenistan");
					add("Turks And Caicos Islands");
					add("Tuvalu");
					add("Uganda");
					add("Ukraine");
					add("United Arab Emirates");
					add("United Kingdom");
					add("United States Minor Outlying Islands");
					add("United States");
					add("Uruguay");
					add("Uzbekistan");
					add("Vanuatu");
					add("Venezuela");
					add("Viet Nam");
					add("Virgin Islands, British");
					add("Virgin Islands, U.S.");
					add("Wallis And Futuna");
					add("Western Sahara");
					add("Yemen");
					add("Yugoslavia");
					add("Zambia");
					add("Zimbabwe");
				}
			});

	private final VerticalPanel panel = new VerticalPanel() {
		{
			add(new Label("Enter country: "));
			add(suggestBox);
		}
	};

	@Override
	public void onModuleLoad() {
		RootPanel.get("slot").add(panel);

	}
}
