using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WoWMemoryManager
{
    public class GuildBankInfo
    {
        public string server;
        public string faction;
        public string playerName;
        public long checkTime;
        public long balance;
        public long delta;

        /// <summary>
        /// </summary>
        /// <param name="raw">String generated by NAddon.lua: NGuildBalance(balance, delta)</param>
        public GuildBankInfo(string raw)
        {
            string[] values = raw.Split(':');
            if (values.Length != 6)
            {
                throw new System.FormatException("Bad guildinfo string from addon (should be 6 ':'-separated strings): '" + raw + "'");
            }

            try
            {
                server = values[0];
                faction = values[1];
                playerName = values[2];
                checkTime = long.Parse(values[3]);
                balance = long.Parse(values[4]);
                delta = long.Parse(values[5]);
            }
            catch (System.FormatException e)
            {
                throw new System.FormatException("Bad guildinfo string from addon (fields 4..6 should contain integer numbers): '" + raw + "'", e);
            }
        }

        public override string ToString()
        {
            return "{ GuidBankInfo: " + server + " / " + faction + " / " + playerName + ": time=" + checkTime + ", balance=" + balance + ", delta=" + delta + " }";
        }
    }
}
